### ISSUE TITLE
XPath for attributes?

### ISSUE THREAD

**Issue by oliverjanik** [beevik/etree#38]
Any way to query an attribute with xpath?

**Comment by beevik** [comment]
There is not currently a way to do this.  The etree paths support only searching for XML elements.

**Comment by oliverjanik** [comment]
What would it look like from API point of view, care to share some thoughts? I might be able to help out.

**Comment by beevik** [comment]
One thing to keep in mind is that etree paths are not really intended to be compatible with XPath.  The syntax is similar, but XPath is much more flexible and powerful than etree paths, which were designed to be simple with a small code footprint.

It would be difficult to make etree paths support finding attributes for a couple reasons:
1. The `Attr` type does not include information about the parent element containing it, so once you found an one, you wouldn't be able to tell where it existed in the DOM.  This might be okay for some special cases, but I imagine it would be problematic in most other cases.
2. The package would require new `FindAttr` and `FindAttrs` functions, which would need to treat paths differently than the existing `FindElement` and `FindElements` functions do. Namely, they'd be expected to have a final segment prefixed with `@`.

With etree as it stands now, you should be able to search for XML elements based on the contents of their attributes.  Is this not sufficient for what you're trying to do?  I'm curious to know why you want to search for attributes.  Is it because you're trying to use a standard XPath?

**Comment by oliverjanik** [comment]
I see. My use is patching xml files (mostly config files) during build/deployment. The path is specified on the command line and I just need a succinct way to say e.g. set value of attribute at path to XY.

Hence the suggestion. I thought it might come in handy for other users of etree.

**Comment by beevik** [comment]
If I could think of an elegant way to make it work, I'd be happy to add it.

Have you considered the [xmlpath](https://godoc.org/launchpad.net/xmlpath) library?  It might be suitable for your use-case.

**Comment by oliverjanik** [comment]
Thanks for the suggestion I'll check it out.

**Comment by beevik** [comment]
Good luck
