### ISSUE TITLE
Cannot find element with ":" in the name.

### ISSUE THREAD

**Issue by legowerewolf** [beevik/etree#46]
XML structure:
```xml
<package xmlns="http://www.idpf.org/2007/opf" unique-identifier="uuid_id" version="2.0">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">
    <dc:identifier opf:scheme="uuid" id="uuid_id"></dc:identifier>
    <dc:title></dc:title>
    <dc:creator opf:role="aut"></dc:creator>
    <dc:language>eng</dc:language>
  </metadata>
</package>
```
Go code: 
```golang
doc.FindElement("/package/metadata/*[1]")).SetText("test") //fails
doc.FindElement("/package/metadata/dc:identifier").SetText("test") //fails
```

**Comment by beevik** [comment]
The problem is not that you are using a namespace (i.e., a tag when a ':' in the name).  It's that you're using an absolute path for your query string.  You cannot use absolute paths with `FindElement` (or with any etree path query).  The code you wrote should have panicked and produced an error telling you this.

You need to use a relative path instead.  In your case, you should do this.

```go
doc.FindElement("./package/metadata/*[1]")).SetText("test")
doc.FindElement("./package/metadata/dc:identifier").SetText("test")
```

This performs a search starting from the document root `doc`.
