### ISSUE TITLE
Cdata is gone

### ISSUE THREAD

**Issue by dfy167** [beevik/etree#74]
when parse xml and then output Cdata is gone
![image](https://user-images.githubusercontent.com/9856271/56940076-c5ab6800-6b3e-11e9-8e4b-efeb0b2ff29c.png)

**Comment by beevik** [comment]
Can you please provide some sample code that will reproduce this?

**Comment by dfy167** [comment]
XML:

**Comment by dfy167** [comment]
![Uploading image.png…]()

**Comment by dfy167** [comment]
![image](https://user-images.githubusercontent.com/9856271/57004932-f0142880-6c05-11e9-8fcc-7916d531f5e2.png)

**Comment by beevik** [comment]
Hm, this appears to be happening because of the way the underlying go's built-in xml decoder works. When it encounters any CDATA  declaration, it reads the contents as arbitrary character data but loses the fact that it was stored as a CDATA declaration.  Since etree is built on top of go's built-in xml decoder. 

I'll do some research to see if there's anything that can be done about this, short of no longer using go's built-in xml decoder.

**Comment by beevik** [comment]
It looks like I was right. Go's built-in xml decoder does not allow me to distinguish between XML character data that was encoded within a CDATA section and XML character data that was not.  I'm afraid that means there is no easy way for etree to solve your problem.  (At least not one of which I am aware.)  You might want to consider using the built-in xml library's [marshalling](https://golang.org/pkg/encoding/xml/#Marshal) support instead.

I'm guessing you already know this, but exporting the XML document with non-CDATA character data still results in a standards-compliant XML document.  But I am guessing you would like to maintain the CDATA sections for a specific reason.

**Comment by dfy167** [comment]
you are right. thanks for you help.
