### ISSUE TITLE
Why Text() use 'break'  but not 'continue'?

### ISSUE THREAD

**Issue by mss1213** [beevik/etree#77]
func (e *Element) Text() string {
	if len(e.Child) == 0 {
		return ""
	}

	text := ""
	for _, ch := range e.Child {
		if cd, ok := ch.(*CharData); ok {
			if text == "" {
				text = cd.Data
			} else {
				text += cd.Data
			}
		} else {
			break
		}
	}
	return text
}
when I used this function to get charData in a tag,a problem happend: an element has two child,and if the first is not CharData,it may not check the second.

**Comment by beevik** [comment]
The `Text()` function is intended to find all contiguous character data immediately following the opening XML element tag.

Consider this XML:

`<node>s1<![CDATA[s2]]>s3</node>`

Calling `Text()` for the `node` element concatenates `s1`, `s2` and `s3` and returns `s1s2s3`.  This is because the character data is entirely contiguous and immediately follows the `<node>` element tag.

Now, consider this XML:

`<node>s1<child></child>s2</node>`

In this case, calling `Text()` returns `s1` instead of `s1s2`.

The purpose of `Text()` is to gather all character data until the first non-character-data token is reached.

**Comment by mss1213** [comment]
I got is,thanks.

**Comment by mss1213** [comment]
I got it,thanks very much.
