### ISSUE TITLE
Some XML prefixes have a colon

### ISSUE THREAD

**Issue by emersion** [beevik/etree#82]
For instance the CardDAV prefix is `urn:ietf:params:xml:ns:carddav`. This doesn't play well with `spaceDecompose`:

https://github.com/beevik/etree/blob/23e6ba8cc2de65cb79fedf9827731040ddd4bdf5/helpers.go#L144

The standard Go library is using a space character, probably because of this. Thoughts?

**Comment by beevik** [comment]
If I'm reading the [XML spec](https://www.w3.org/TR/xml-names/#ns-qualnames) correctly, XML namespace prefixes should not contain colon characters.

```
 QName          ::= PrefixedName  | UnprefixedName
 PrefixedName   ::= Prefix ':' LocalPart
 UnprefixedName ::= LocalPart
 Prefix         ::= NCName
 LocalPart      ::= NCName
 NCName         ::= Name - (Char* ':' Char*)     /* An XML Name, minus the ":" */
```

Nevertheless, it would be an easy fix to make `spaceDecompose` use the last ':' as its splitting point instead of the first one.  If I changed `spaceDecompose` to this:

```go
func spaceDecompose(str string) (space, key string) {
	colon := strings.LastIndexByte(str, ':')
	if colon == -1 {
		return "", str
	}
	return str[:colon], str[colon+1:]
}
```

Would that fix your CardDAV case?

**Comment by Ferada** [comment]
It's not the prefix that contains the colons, it's the namespace, [e.g.](https://github.com/dmfs/davwiki/wiki/urn%3Aietf%3Aparams%3Axml%3Ans%3Acaldav%3Acalendar-description):

```
<C:calendar-description xml:lang="fr-CA"
    xmlns:C="urn:ietf:params:xml:ns:caldav"
>Calendrier de Mathilde Desruisseaux</C:calendar-description>
```
