### ISSUE TITLE
Indent does not preserve spaces

### ISSUE THREAD

**Issue by neclepsio** [beevik/etree#88]
When calling Indent(2) on this snipplet, taken from Word document, it gets transformed in a way that breaks the document itself.

            <w:r w:rsidR="002A2378">
                <w:t xml:space="preserve"> </w:t>
            </w:r>

Becomes:

            <w:r w:rsidR="002A2378">
                <w:t xml:space="preserve"/>
            </w:r>

**Comment by beevik** [comment]
Hm, this is an interesting case.  For the purposes of indenting, `etree` treats whitespace characters between XML tags (like `<w:t>` and `</w:t>`) as unimportant so long as there are no non-whitespace characters included.  In your example, the simple space between the tags is considered "unimportant" and is therefore removed when the document is re-indented.  Normally this is what you want.  Otherwise indenting an XML string like the following would not be possible:
```xml
<abc> <def> </def> </abc>
```
In your example, however, it's obviously not what you want.  

I suspect the Word XML parser had to addess a similar issue, which is why they introduced an `xml:space` attribute with the value of `"preserve"`.  Unfortunately, I'm not seeing an obvious way to handle your specific case without breaking the common case.

I'll give this some more thought.

**Comment by ddy4633** [comment]
Hello I also encountered the same problem, it will convert in a way that destroys the document itself. Causes my business to load abnormally. Is there any way to avoid this reduced conversion?

**Comment by beevik** [comment]
I added a feature to support this request.  See this commit: https://github.com/beevik/etree/commit/335c3797e63737a725d4fe63f2275ce83b11ab26.  To use it, add the following code before calling `doc.Indent` or `doc.IndentTabs`:

```go
doc.WriteSettings.PreserveLeafWhitespace = true
```
